// seed.js
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  /* 
 const products = [
    // phones
    {
      name: "Samsung Galaxy S26 Ultra",
      status: "active",
      src: "https://images.samsung.com/is/image/samsung/assets/global/galaxy-s26-ultra/images/galaxy-s26-ultra-titanium-black.jpg",
      description: "Flagship with advanced AI camera and S Pen",
      brand: "Samsung",
      category: "phones",
      number_in_stock: 35,
      colors: ["Titanium Black", "Titanium Silver"],
      sizes: [],
      price: 1299.0,
      shipping: 0.0,
      tax: 10.0,
      reviewCount: 180,
      reviewSum: 810,
    },
    {
      name: "Apple iPhone 17 Pro Max",
      status: "active",
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-17-pro-max-natural-titanium-select?wid=940&hei=1112",
      description: "Premium iPhone with A19 chip and pro camera",
      brand: "Apple",
      category: "phones",
      number_in_stock: 28,
      colors: ["Natural Titanium", "Black Titanium"],
      sizes: [],
      price: 1399.0,
      shipping: 15.0,
      tax: 12.0,
      reviewCount: 210,
      reviewSum: 940,
    },
    {
      name: "Google Pixel 10 Pro",
      status: "active",
      src: "https://store.google.com/images/branding/product/1x/pixel_10_pro_porcelain.jpg",
      description: "AI-powered photography and clean Android",
      brand: "Google",
      category: "phones",
      number_in_stock: 42,
      colors: ["Porcelain", "Obsidian"],
      sizes: [],
      price: 999.0,
      shipping: 0.0,
      tax: 8.0,
      reviewCount: 145,
      reviewSum: 650,
    },

    // smartTv
    {
      name: 'Samsung S95F OLED 65"',
      status: "active",
      src: "https://images.samsung.com/is/image/samsung/p6pim/au/qd-oled-tv/qa65s95fakxxu/gallery/qa65s95fakxxu-541001-au-01.jpg",
      description: "QD-OLED with peak brightness and anti-glare",
      brand: "Samsung",
      category: "smartTv",
      number_in_stock: 15,
      colors: ["Black"],
      sizes: ["55", "65", "77"],
      price: 2499.0,
      shipping: 60.0,
      tax: 15.0,
      reviewCount: 95,
      reviewSum: 420,
    },
    {
      name: 'LG G5 OLED 65"',
      status: "active",
      src: "https://www.lg.com/us/images/tvs/md07581429/gallery/medium01.jpg",
      description: "OLED evo with perfect blacks and Dolby Vision",
      brand: "LG",
      category: "smartTv",
      number_in_stock: 18,
      colors: ["Black"],
      sizes: ["55", "65", "77"],
      price: 2199.0,
      shipping: 50.0,
      tax: 14.0,
      reviewCount: 110,
      reviewSum: 490,
    },
    {
      name: 'Sony Bravia 8 II 65"',
      status: "active",
      src: "https://www.sony.com/image/sonycorporationgroup/00200000000000000000000000000000/K65XR80.jpg",
      description: "Cognitive Processor XR for cinematic picture",
      brand: "Sony",
      category: "smartTv",
      number_in_stock: 12,
      colors: ["Black"],
      sizes: ["55", "65", "77"],
      price: 2299.0,
      shipping: 55.0,
      tax: 14.0,
      reviewCount: 85,
      reviewSum: 380,
    },

    // Laptops
    {
      name: 'Apple MacBook Air M4 15"',
      status: "active",
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-15-midnight-select?wid=904&hei=840",
      description: "Powerful M4 chip, long battery life",
      brand: "Apple",
      category: "Laptops",
      number_in_stock: 30,
      colors: ["Midnight", "Starlight"],
      sizes: ["13", "15"],
      price: 1299.0,
      shipping: 20.0,
      tax: 10.0,
      reviewCount: 120,
      reviewSum: 540,
    },
    {
      name: "Dell XPS 14 2026",
      status: "active",
      src: "https://i.dell.com/is/image/DellContent/content/dam/global-asset-library/Products/Laptops/XPS/14/9640/xps-14-9640-laptop-black-2up.png",
      description: "Premium ultrabook with OLED option",
      brand: "Dell",
      category: "Laptops",
      number_in_stock: 22,
      colors: ["Platinum", "Graphite"],
      sizes: [],
      price: 1699.0,
      shipping: 0.0,
      tax: 9.0,
      reviewCount: 78,
      reviewSum: 350,
    },
    {
      name: "Microsoft Surface Laptop 7",
      status: "active",
      src: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE5fX0X?ver=5e5f",
      description: "Snapdragon X Elite for efficiency",
      brand: "Microsoft",
      category: "Laptops",
      number_in_stock: 25,
      colors: ["Platinum"],
      sizes: [],
      price: 1199.0,
      shipping: 15.0,
      tax: 9.0,
      reviewCount: 90,
      reviewSum: 400,
    },

    // headsets
    {
      name: "Sony WH-1000XM6",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61e9r0+2pVL._AC_SL1500_.jpg",
      description: "Best-in-class ANC over-ear",
      brand: "Sony",
      category: "headsets",
      number_in_stock: 50,
      colors: ["Black", "Silver"],
      sizes: [],
      price: 399.0,
      shipping: 0.0,
      tax: 7.0,
      reviewCount: 320,
      reviewSum: 1400,
    },
    {
      name: "Bose QuietComfort Ultra",
      status: "active",
      src: "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/headphones/quietcomfort-ultra-headphones/images/qc-ultra-headphones-black-ec.png",
      description: "Immersive audio and comfort",
      brand: "Bose",
      category: "headsets",
      number_in_stock: 45,
      colors: ["Black"],
      sizes: [],
      price: 429.0,
      shipping: 10.0,
      tax: 8.0,
      reviewCount: 280,
      reviewSum: 1250,
    },
    {
      name: "Apple AirPods Max",
      status: "active",
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-spacegray-202011?wid=940&hei=1112",
      description: "Spatial audio over-ear premium",
      brand: "Apple",
      category: "headsets",
      number_in_stock: 38,
      colors: ["Space Gray"],
      sizes: [],
      price: 549.0,
      shipping: 0.0,
      tax: 10.0,
      reviewCount: 190,
      reviewSum: 850,
    },

    // watches
    {
      name: "Apple Watch Ultra 3",
      status: "active",
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/watch-ultra-3-natural-titanium?wid=940&hei=1112",
      description: "Rugged adventure smartwatch",
      brand: "Apple",
      category: "watches",
      number_in_stock: 55,
      colors: ["Natural Titanium"],
      sizes: ["49mm"],
      price: 799.0,
      shipping: 0.0,
      tax: 9.0,
      reviewCount: 140,
      reviewSum: 620,
    },
    {
      name: "Samsung Galaxy Watch 8",
      status: "active",
      src: "https://images.samsung.com/is/image/samsung/p6pim/au/galaxy-watch/galaxy-watch-ultra-titanium-gray-sm-l705nzaaxsa/gallery/galaxy-watch-ultra-titanium-gray-sm-l705nzaaxsa-541001-au-01.jpg",
      description: "Advanced health tracking Wear OS",
      brand: "Samsung",
      category: "watches",
      number_in_stock: 48,
      colors: ["Titanium Gray"],
      sizes: ["44mm"],
      price: 449.0,
      shipping: 0.0,
      tax: 7.5,
      reviewCount: 110,
      reviewSum: 480,
    },
    {
      name: "Google Pixel Watch 4",
      status: "active",
      src: "https://store.google.com/images/branding/product/1x/pixel_watch_4_porcelain_01.jpg",
      description: "Elegant design with Fitbit features",
      brand: "Google",
      category: "watches",
      number_in_stock: 40,
      colors: ["Porcelain"],
      sizes: ["41mm"],
      price: 349.0,
      shipping: 0.0,
      tax: 6.0,
      reviewCount: 95,
      reviewSum: 410,
    },

    // wallets
    {
      name: "Leatherology Thin Bifold",
      status: "active",
      src: "https://www.leatherology.com/cdn/shop/products/Thin_Bifold_Wallet_Black_Onyx_Front_1200x.jpg",
      description: "Slim full-grain leather bifold",
      brand: "Leatherology",
      category: "wallets",
      number_in_stock: 60,
      colors: ["Black", "Brown"],
      sizes: [],
      price: 75.0,
      shipping: 5.0,
      tax: 5.0,
      reviewCount: 220,
      reviewSum: 950,
    },
    {
      name: "Shinola Slim Bifold",
      status: "active",
      src: "https://www.shinola.com/dw/image/v2/BBBW_PRD/on/demandware.static/-/Sites-Shinola-Library/default/dwexample/shinola-slim-bifold-wallet-black.jpg",
      description: "Premium American leather wallet",
      brand: "Shinola",
      category: "wallets",
      number_in_stock: 55,
      colors: ["Black"],
      sizes: [],
      price: 195.0,
      shipping: 8.0,
      tax: 6.0,
      reviewCount: 150,
      reviewSum: 680,
    },
    {
      name: "Bellroy Hide & Seek",
      status: "active",
      src: "https://bellroy.com/cdn/shop/products/Hide_Seek_Wallet_Ranger_Green_Front_1200x.jpg",
      description: "Slim card-focused leather wallet",
      brand: "Bellroy",
      category: "wallets",
      number_in_stock: 70,
      colors: ["Ranger Green"],
      sizes: [],
      price: 89.0,
      shipping: 0.0,
      tax: 5.0,
      reviewCount: 300,
      reviewSum: 1350,
    },

    // jewelry (example with popular items)
    {
      name: "Tiffany T Smile Pendant",
      status: "active",
      src: "https://www.tiffany.com/content/dam/tiffany-com/ti-pdp/Tiffany-T-Smile-Pendant-18k-yellow-gold-123456789.jpg",
      description: "Iconic smile pendant in gold",
      brand: "Tiffany",
      category: "jewelry",
      number_in_stock: 25,
      colors: ["Yellow Gold"],
      sizes: [],
      price: 1200.0,
      shipping: 20.0,
      tax: 12.0,
      reviewCount: 80,
      reviewSum: 360,
    },
    {
      name: "Cartier Love Bracelet",
      status: "active",
      src: "https://www.cartier.com/dw/image/v2/BFHR_PRD/on/demandware.static/-/Sites-cartier-master/default/dwexample/love-bracelet-yellow-gold.jpg",
      description: "Classic screw bracelet",
      brand: "Cartier",
      category: "jewelry",
      number_in_stock: 18,
      colors: ["Yellow Gold"],
      sizes: [],
      price: 7500.0,
      shipping: 30.0,
      tax: 15.0,
      reviewCount: 65,
      reviewSum: 290,
    },
    {
      name: "Pandora Charm Bracelet",
      status: "active",
      src: "https://pandora.com/dw/image/v2/BFHR_PRD/on/demandware.static/-/Sites-pandora-master/default/dwexample/moments-bracelet.jpg",
      description: "Customizable charm bracelet",
      brand: "Pandora",
      category: "jewelry",
      number_in_stock: 45,
      colors: ["Silver"],
      sizes: [],
      price: 85.0,
      shipping: 5.0,
      tax: 5.0,
      reviewCount: 400,
      reviewSum: 1800,
    },

    // jeHats (assuming hats / caps)
    {
      name: "New Era 9FIFTY Snapback",
      status: "active",
      src: "https://www.neweracap.com/cdn/shop/products/NE_9FIFTY_Black.jpg",
      description: "Classic snapback cap",
      brand: "New Era",
      category: "jeHats",
      number_in_stock: 80,
      colors: ["Black", "Navy"],
      sizes: ["One Size"],
      price: 35.0,
      shipping: 5.0,
      tax: 4.0,
      reviewCount: 250,
      reviewSum: 1100,
    },
    {
      name: "Supreme Bucket Hat",
      status: "active",
      src: "https://supreme.com/dw/image/v2/BFHR_PRD/on/demandware.static/-/Sites-supreme-master/default/dwexample/bucket-hat.jpg",
      description: "Streetwear bucket hat",
      brand: "Supreme",
      category: "jeHats",
      number_in_stock: 40,
      colors: ["Red"],
      sizes: [],
      price: 48.0,
      shipping: 6.0,
      tax: 5.0,
      reviewCount: 180,
      reviewSum: 800,
    },
    {
      name: "Patagonia Trucker Hat",
      status: "active",
      src: "https://www.patagonia.com/dw/image/v2/BFHR_PRD/on/demandware.static/-/Sites-patagonia-master/default/dwexample/trucker-hat.jpg",
      description: "Eco-friendly trucker cap",
      brand: "Patagonia",
      category: "jeHats",
      number_in_stock: 65,
      colors: ["Green"],
      sizes: ["Adjustable"],
      price: 35.0,
      shipping: 0.0,
      tax: 4.0,
      reviewCount: 200,
      reviewSum: 900,
    },

    // sofas
    {
      name: "IKEA FRIHETEN Sofa Bed",
      status: "active",
      src: "https://www.ikea.com/us/en/images/products/friheten-sleeper-sofa-skiftebo-dark-gray__0814621_pe772499_s5.jpg",
      description: "Convertible sofa bed",
      brand: "IKEA",
      category: "sofas",
      number_in_stock: 20,
      colors: ["Dark Gray"],
      sizes: [],
      price: 499.0,
      shipping: 80.0,
      tax: 10.0,
      reviewCount: 150,
      reviewSum: 650,
    },
    {
      name: "West Elm Harmony Sofa",
      status: "active",
      src: "https://www.westelm.com/weimgs/rk/images/wcm/products/2025/01/123456/harmony-sofa.jpg",
      description: "Modern sectional sofa",
      brand: "West Elm",
      category: "sofas",
      number_in_stock: 12,
      colors: ["Beige"],
      sizes: [],
      price: 1899.0,
      shipping: 150.0,
      tax: 12.0,
      reviewCount: 90,
      reviewSum: 400,
    },
    {
      name: "Article Sven Sofa",
      status: "active",
      src: "https://article.com/image/12345/sven-sofa.jpg",
      description: "Mid-century modern sofa",
      brand: "Article",
      category: "sofas",
      number_in_stock: 15,
      colors: ["Green"],
      sizes: [],
      price: 1299.0,
      shipping: 100.0,
      tax: 10.0,
      reviewCount: 110,
      reviewSum: 480,
    },

    // beds (similar pattern for remaining categories)
    // gardening
    {
      name: "Gardena Garden Hose",
      status: "active",
      src: "https://www.gardena.com/int/images/products/hoses/garden-hose.jpg",
      description: "Durable 50ft garden hose",
      brand: "Gardena",
      category: "gardening",
      number_in_stock: 60,
      colors: ["Green"],
      sizes: [],
      price: 45.0,
      shipping: 10.0,
      tax: 5.0,
      reviewCount: 130,
      reviewSum: 580,
    },
    {
      name: "Miracle-Gro Potting Mix",
      status: "active",
      src: "https://www.miraclegro.com/images/products/potting-mix.jpg",
      description: "All-purpose potting soil",
      brand: "Miracle-Gro",
      category: "gardening",
      number_in_stock: 100,
      colors: [],
      sizes: [],
      price: 15.0,
      shipping: 5.0,
      tax: 3.0,
      reviewCount: 300,
      reviewSum: 1350,
    },
    {
      name: "Fiskars Pruning Shears",
      status: "active",
      src: "https://www.fiskars.com/images/products/pruning-shears.jpg",
      description: "Bypass pruning shears",
      brand: "Fiskars",
      category: "gardening",
      number_in_stock: 75,
      colors: ["Orange"],
      sizes: [],
      price: 25.0,
      shipping: 5.0,
      tax: 4.0,
      reviewCount: 220,
      reviewSum: 980,
    },

    // utensils
    {
      name: "OXO Good Grips Utensil Set",
      status: "active",
      src: "https://www.oxo.com/images/products/utensil-set.jpg",
      description: "Kitchen utensil 15-piece set",
      brand: "OXO",
      category: "utensils",
      number_in_stock: 50,
      colors: ["Black"],
      sizes: [],
      price: 59.0,
      shipping: 8.0,
      tax: 5.0,
      reviewCount: 280,
      reviewSum: 1250,
    },
    {
      name: "All-Clad Stainless Utensils",
      status: "active",
      src: "https://www.all-clad.com/images/products/utensils.jpg",
      description: "Premium stainless steel tools",
      brand: "All-Clad",
      category: "utensils",
      number_in_stock: 30,
      colors: ["Silver"],
      sizes: [],
      price: 99.0,
      shipping: 10.0,
      tax: 6.0,
      reviewCount: 140,
      reviewSum: 620,
    },
    {
      name: "Zwilling Twin Chef Set",
      status: "active",
      src: "https://www.zwilling.com/images/products/chef-set.jpg",
      description: "High-quality kitchen utensils",
      brand: "Zwilling",
      category: "utensils",
      number_in_stock: 40,
      colors: ["Black"],
      sizes: [],
      price: 79.0,
      shipping: 8.0,
      tax: 5.0,
      reviewCount: 190,
      reviewSum: 850,
    },

    // skincare
    {
      name: "CeraVe Hydrating Cleanser",
      status: "active",
      src: "https://www.cerave.com/images/products/hydrating-cleanser.jpg",
      description: "Gentle daily face cleanser",
      brand: "CeraVe",
      category: "skincare",
      number_in_stock: 120,
      colors: [],
      sizes: [],
      price: 14.99,
      shipping: 0.0,
      tax: 3.0,
      reviewCount: 500,
      reviewSum: 2200,
    },
    {
      name: "The Ordinary Niacinamide",
      status: "active",
      src: "https://theordinary.com/images/products/niacinamide-serum.jpg",
      description: "Serum for blemishes and pores",
      brand: "The Ordinary",
      category: "skincare",
      number_in_stock: 90,
      colors: [],
      sizes: [],
      price: 6.0,
      shipping: 0.0,
      tax: 2.0,
      reviewCount: 800,
      reviewSum: 3600,
    },
    {
      name: "La Roche-Posay Toleriane",
      status: "active",
      src: "https://www.laroche-posay.us/images/products/toleriane-moisturizer.jpg",
      description: "Sensitive skin moisturizer",
      brand: "La Roche-Posay",
      category: "skincare",
      number_in_stock: 70,
      colors: [],
      sizes: [],
      price: 24.99,
      shipping: 5.0,
      tax: 4.0,
      reviewCount: 400,
      reviewSum: 1800,
    },

    /// MAKEUP 
    {
      name: "Fenty Pro Filt'r",
      status: "active",
      src: "https://www.fentybeauty.com/dw/image/v2/BDBW_PRD/on/demandware.static/-/Sites-itemmaster_fenty/default/dw1b3c8f8a/images/10001_v1.jpg",
      description: "Soft matte longwear foundation",
      brand: "Fenty Beauty",
      category: "makeup",
      number_in_stock: 120,
      colors: ["420", "240"],
      sizes: ["32ml"],
      price: 40.0,
      shipping: 0.0,
      tax: 3.2,
      reviewCount: 1500,
      reviewSum: 7200,
    },
    {
      name: "MAC Retro Matte",
      status: "active",
      src: "https://www.maccosmetics.com/media/export/cms/products/640x600/mac_sku_M1AY01_640x600_0.jpg",
      description: "Classic Ruby Woo lipstick",
      brand: "MAC",
      category: "makeup",
      number_in_stock: 200,
      colors: ["Red"],
      sizes: ["3g"],
      price: 23.0,
      shipping: 5.0,
      tax: 1.84,
      reviewCount: 800,
      reviewSum: 3840,
    },
    {
      name: "NARS Radiant Concealer",
      status: "active",
      src: "https://www.narscosmetics.com/dw/image/v2/BDBM_PRD/on/demandware.static/-/Sites-itemmaster_nars/default/dw6c6c7b7a/hi-res/0607845012344.jpg",
      description: "Creamy multi-action concealer",
      brand: "NARS",
      category: "makeup",
      number_in_stock: 90,
      colors: ["Custard", "Ginger"],
      sizes: ["6ml"],
      price: 32.0,
      shipping: 0.0,
      tax: 2.56,
      reviewCount: 1200,
      reviewSum: 5760,
    },

    // HAIRCARE 
    {
      name: "Olaplex No. 3",
      status: "active",
      src: "https://olaplex.com/cdn/shop/files/No.3_HairPerfector_100ml.jpg",
      description: "Hair repairing treatment",
      brand: "Olaplex",
      category: "haircare",
      number_in_stock: 85,
      colors: [],
      sizes: ["100ml"],
      price: 30.0,
      shipping: 5.0,
      tax: 2.4,
      reviewCount: 3200,
      reviewSum: 15360,
    },
    {
      name: "Dyson Airwrap",
      status: "active",
      src: "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-poland/products/hair-care/airwrap/400714-01.png",
      description: "Multi-styler and dryer",
      brand: "Dyson",
      category: "haircare",
      number_in_stock: 15,
      colors: ["Nickel", "Copper"],
      sizes: [],
      price: 599.99,
      shipping: 0.0,
      tax: 48.0,
      reviewCount: 450,
      reviewSum: 2160,
    },
    {
      name: "Moroccanoil Treatment",
      status: "active",
      src: "https://www.moroccanoil.com/cdn/shop/products/Moroccanoil_Treatment_100ml_Front.jpg",
      description: "Argan oil hair treatment",
      brand: "Moroccanoil",
      category: "haircare",
      number_in_stock: 110,
      colors: [],
      sizes: ["100ml"],
      price: 48.0,
      shipping: 0.0,
      tax: 3.84,
      reviewCount: 980,
      reviewSum: 4704,
    },

    //FRAGRANCE 
    {
      name: "Chanel No. 5",
      status: "active",
      src: "https://www.chanel.com/images/t_one/t_fragrance//h_600,w_600,f_auto,q_auto/v1/f_fragrance/p125530/n-5-eau-de-parfum-spray-3-4fl-oz.jpg",
      description: "Timeless floral bouquet",
      brand: "Chanel",
      category: "fragrance",
      number_in_stock: 40,
      colors: [],
      sizes: ["100ml"],
      price: 165.0,
      shipping: 0.0,
      tax: 13.2,
      reviewCount: 2100,
      reviewSum: 10080,
    },
    {
      name: "Bleu de Chanel",
      status: "active",
      src: "https://www.chanel.com/images/t_one/t_fragrance//h_600,w_600,f_auto,q_auto/v1/f_fragrance/p107460/bleu-de-chanel-eau-de-parfum-spray-3-4fl-oz.jpg",
      description: "Woody aromatic fragrance",
      brand: "Chanel",
      category: "fragrance",
      number_in_stock: 55,
      colors: [],
      sizes: ["100ml"],
      price: 130.0,
      shipping: 0.0,
      tax: 10.4,
      reviewCount: 1800,
      reviewSum: 8820,
    },
    {
      name: "Replica By the Fireplace",
      status: "active",
      src: "https://www.maisonmargiela-fragrances.us/dw/image/v2/AABR_PRD/on/demandware.static/-/Sites-mm-master-catalog/default/dw8d5d1c3a/images/3605522106520_1.jpg",
      description: "Warm and spicy scents",
      brand: "Maison Margiela",
      category: "fragrance",
      number_in_stock: 35,
      colors: [],
      sizes: ["100ml"],
      price: 160.0,
      shipping: 0.0,
      tax: 12.8,
      reviewCount: 640,
      reviewSum: 3072,
    },

    // GYM 
    {
      name: "Rogue Ohio Bar",
      status: "active",
      src: "https://www.roguefitness.com/media/catalog/product/o/h/ohio-bar-black-zinc-1.jpg",
      description: "Standard training barbell",
      brand: "Rogue",
      category: "gym",
      number_in_stock: 25,
      colors: ["Black"],
      sizes: ["20kg"],
      price: 295.0,
      shipping: 25.0,
      tax: 23.6,
      reviewCount: 520,
      reviewSum: 2548,
    },
    {
      name: "Bowflex SelectTech 552",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71Yf9A-G9gL._AC_SL1500_.jpg",
      description: "Adjustable dumbbells",
      brand: "Bowflex",
      category: "gym",
      number_in_stock: 18,
      colors: ["Black"],
      sizes: ["52.5lbs"],
      price: 429.0,
      shipping: 40.0,
      tax: 34.32,
      reviewCount: 1200,
      reviewSum: 5760,
    },
    {
      name: "Concept2 RowErg",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61NfT-j399L._AC_SL1500_.jpg",
      description: "Indoor rowing machine",
      brand: "Concept2",
      category: "gym",
      number_in_stock: 10,
      colors: ["Black"],
      sizes: [],
      price: 990.0,
      shipping: 50.0,
      tax: 79.2,
      reviewCount: 890,
      reviewSum: 4405,
    },

    // BANDS 
    {
      name: "Fitbit Charge 6",
      status: "active",
      src: "https://m.media-amazon.com/images/I/6166V2v+V2L._AC_SL1500_.jpg",
      description: "Fitness tracker with heart rate",
      brand: "Fitbit",
      category: "bands",
      number_in_stock: 65,
      colors: ["Black", "Coral"],
      sizes: ["S", "L"],
      price: 159.95,
      shipping: 0.0,
      tax: 12.8,
      reviewCount: 310,
      reviewSum: 1426,
    },
    {
      name: "Whoop 4.0",
      status: "active",
      src: "https://m.media-amazon.com/images/I/51HDeJ2UfPL._AC_SL1000_.jpg",
      description: "Subscription fitness tracker",
      brand: "Whoop",
      category: "bands",
      number_in_stock: 100,
      colors: ["Onyx"],
      sizes: [],
      price: 0.0,
      shipping: 0.0,
      tax: 0.0,
      reviewCount: 200,
      reviewSum: 800,
    },
    {
      name: "Theraband Set",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71X8kEwK1dL._AC_SL1500_.jpg",
      description: "Resistance exercise bands",
      brand: "Theraband",
      category: "bands",
      number_in_stock: 200,
      colors: ["Yellow", "Red", "Green"],
      sizes: [],
      price: 19.99,
      shipping: 5.0,
      tax: 1.6,
      reviewCount: 450,
      reviewSum: 2160,
    },

    // SOCCER 
    {
      name: "Adidas Al Rihla",
      status: "active",
      src: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7b7956328b0b4672aa86ae2c00f68153_9366/Al_Rihla_Pro_Ball_White_H57783_01_standard.jpg",
      description: "FIFA World Cup official ball",
      brand: "Adidas",
      category: "soccer",
      number_in_stock: 45,
      colors: ["White"],
      sizes: ["5"],
      price: 165.0,
      shipping: 0.0,
      tax: 13.2,
      reviewCount: 320,
      reviewSum: 1568,
    },
    {
      name: "Nike Mercurial Vapor",
      status: "active",
      src: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/2b7e1c9d-d8c3-4d0c-8f6a-6f6a7d8d9e0f/mercurial-vapor-15-pro-fg.png",
      description: "Firm-ground soccer cleats",
      brand: "Nike",
      category: "soccer",
      number_in_stock: 38,
      colors: ["Blue", "Volt"],
      sizes: ["9", "10", "11"],
      price: 150.0,
      shipping: 0.0,
      tax: 12.0,
      reviewCount: 210,
      reviewSum: 1008,
    },
    {
      name: "Kwik Goal Net",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81D7mGfR+GL._AC_SL1500_.jpg",
      description: "Portable training goal",
      brand: "Kwik Goal",
      category: "soccer",
      number_in_stock: 15,
      colors: ["White"],
      sizes: ["6x12ft"],
      price: 280.0,
      shipping: 30.0,
      tax: 22.4,
      reviewCount: 95,
      reviewSum: 456,
    },

    // SPORTWEAR 
    {
      name: "Lululemon Align Pant",
      status: "active",
      src: "https://images.lululemon.com/is/image/lululemon/LW5DGSS_0001_1",
      description: "High-rise yoga leggings",
      brand: "Lululemon",
      category: "sportwear",
      number_in_stock: 150,
      colors: ["Black", "Navy"],
      sizes: ["4", "6", "8"],
      price: 98.0,
      shipping: 0.0,
      tax: 7.84,
      reviewCount: 4500,
      reviewSum: 21600,
    },
    {
      name: "Nike Dri-FIT Tee",
      status: "active",
      src: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/a1c1d1e1-b1b1-c1c1-d1d1-e1e1f1f1g1g1/dri-fit-mens-training-t-shirt.png",
      description: "Moisture-wicking training shirt",
      brand: "Nike",
      category: "sportwear",
      number_in_stock: 300,
      colors: ["Gray", "Black"],
      sizes: ["M", "L", "XL"],
      price: 30.0,
      shipping: 5.0,
      tax: 2.4,
      reviewCount: 780,
      reviewSum: 3666,
    },
    {
      name: "Under Armour Shorts",
      status: "active",
      src: "https://underarmour.scene7.com/is/image/UnderArmour/V5-1361508-001_FC",
      description: "Loose fit gym shorts",
      brand: "Under Armour",
      category: "sportwear",
      number_in_stock: 250,
      colors: ["Black"],
      sizes: ["L", "XL"],
      price: 25.0,
      shipping: 5.0,
      tax: 2.0,
      reviewCount: 420,
      reviewSum: 1974,
    },

    // EDUCATION TOYS 
    {
      name: "Osmo Genius Starter Kit",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71N1u6+8VfL._AC_SL1500_.jpg",
      description: "Interactive learning games",
      brand: "Osmo",
      category: "educationToys",
      number_in_stock: 40,
      colors: [],
      sizes: ["iPad Base"],
      price: 99.99,
      shipping: 0.0,
      tax: 8.0,
      reviewCount: 1100,
      reviewSum: 5280,
    },
    {
      name: "National Geographic Slime Kit",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81vW-3C7hEL._AC_SL1500_.jpg",
      description: "Science lab for kids",
      brand: "National Geographic",
      category: "educationToys",
      number_in_stock: 80,
      colors: [],
      sizes: [],
      price: 24.99,
      shipping: 5.0,
      tax: 2.0,
      reviewCount: 850,
      reviewSum: 4080,
    },
    {
      name: "Snap Circuits Jr.",
      status: "active",
      src: "https://m.media-amazon.com/images/I/91PshO-rSXL._AC_SL1500_.jpg",
      description: "Electronics discovery kit",
      brand: "Elenco",
      category: "educationToys",
      number_in_stock: 60,
      colors: [],
      sizes: ["SC-100"],
      price: 35.0,
      shipping: 0.0,
      tax: 2.8,
      reviewCount: 2400,
      reviewSum: 11520,
    },

    // MUSICAL TOYS 
    {
      name: "Fisher-Price Piano",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71O0hT-1WqL._AC_SL1500_.jpg",
      description: "Kick & Play piano gym",
      brand: "Fisher-Price",
      category: "musicalToys",
      number_in_stock: 50,
      colors: ["Green"],
      sizes: [],
      price: 44.99,
      shipping: 0.0,
      tax: 3.6,
      reviewCount: 15000,
      reviewSum: 72000,
    },
    {
      name: "VTech Record & Learn KidiStudio",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71V2x2IqWkL._AC_SL1500_.jpg",
      description: "Interactive DJ studio toy",
      brand: "VTech",
      category: "musicalToys",
      number_in_stock: 35,
      colors: ["Orange"],
      sizes: [],
      price: 39.99,
      shipping: 0.0,
      tax: 3.2,
      reviewCount: 920,
      reviewSum: 4324,
    },
    {
      name: "Loog Mini Guitar",
      status: "active",
      src: "https://loog-guitars.myshopify.com/cdn/shop/products/Loog-Mini-Red-1_1024x1024.jpg",
      description: "3-string acoustic guitar",
      brand: "Loog",
      category: "musicalToys",
      number_in_stock: 20,
      colors: ["Red"],
      sizes: ["Mini"],
      price: 89.0,
      shipping: 10.0,
      tax: 7.12,
      reviewCount: 210,
      reviewSum: 987,
    },

    // BIKES 
    {
      name: "Schwinn Kempton",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81vR1I7nQPL._AC_SL1500_.jpg",
      description: "Hybrid comfort bike",
      brand: "Schwinn",
      category: "bikes",
      number_in_stock: 12,
      colors: ["Silver"],
      sizes: ["Large"],
      price: 450.0,
      shipping: 50.0,
      tax: 36.0,
      reviewCount: 180,
      reviewSum: 810,
    },
    {
      name: "Specialized Rockhopper",
      status: "active",
      src: "https://assets.specialized.com/s7er/is/image/Specialized/91522-55_ROCKHOPPER-29-CSTWHT-SMOKE_HERO",
      description: "Entry-level mountain bike",
      brand: "Specialized",
      category: "bikes",
      number_in_stock: 8,
      colors: ["White"],
      sizes: ["29"],
      price: 750.0,
      shipping: 0.0,
      tax: 60.0,
      reviewCount: 340,
      reviewSum: 1632,
    },
    {
      name: "Strider 12 Sport",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71KEnpI6vWL._AC_SL1500_.jpg",
      description: "Toddler balance bike",
      brand: "Strider",
      category: "bikes",
      number_in_stock: 40,
      colors: ["Blue"],
      sizes: ["12 inch"],
      price: 129.0,
      shipping: 0.0,
      tax: 10.32,
      reviewCount: 2200,
      reviewSum: 10780,
    },

    // PRETEND PLAY 
    {
      name: "Melissa & Doug Kitchen",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81rM5Zf1D2L._AC_SL1500_.jpg",
      description: "Chef's play kitchen set",
      brand: "Melissa & Doug",
      category: "pretendPlay",
      number_in_stock: 25,
      colors: ["Charcoal"],
      sizes: [],
      price: 189.0,
      shipping: 20.0,
      tax: 15.12,
      reviewCount: 3100,
      reviewSum: 14880,
    },
    {
      name: "KidKraft Dollhouse",
      status: "active",
      src: "https://m.media-amazon.com/images/I/91r6K6u5Q8L._AC_SL1500_.jpg",
      description: "Majestic Mansion house",
      brand: "KidKraft",
      category: "pretendPlay",
      number_in_stock: 15,
      colors: [],
      sizes: ["Large"],
      price: 149.0,
      shipping: 25.0,
      tax: 11.92,
      reviewCount: 4200,
      reviewSum: 20160,
    },
    {
      name: "Step2 Grill Set",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71H2N2Z-uDL._AC_SL1500_.jpg",
      description: "Backyard barbecue toy",
      brand: "Step2",
      category: "pretendPlay",
      number_in_stock: 30,
      colors: [],
      sizes: [],
      price: 35.0,
      shipping: 10.0,
      tax: 2.8,
      reviewCount: 850,
      reviewSum: 4080,
    },

    // DOLLS 
    {
      name: "Barbie Dreamhouse Doll",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81N7v1rL3rL._AC_SL1500_.jpg",
      description: "Standard fashion barbie",
      brand: "Mattel",
      category: "dolls",
      number_in_stock: 100,
      colors: [],
      sizes: [],
      price: 15.99,
      shipping: 5.0,
      tax: 1.28,
      reviewCount: 12000,
      reviewSum: 57600,
    },
    {
      name: "American Girl Julie",
      status: "active",
      src: "https://www.americangirl.com/dw/image/v2/BAMB_PRD/on/demandware.static/-/Sites-ag-master-catalog/default/dw1d9f8a1a/images/product/F9142_Julie_Doll_01.jpg",
      description: "Historical character doll",
      brand: "American Girl",
      category: "dolls",
      number_in_stock: 20,
      colors: [],
      sizes: ["18 inch"],
      price: 115.0,
      shipping: 0.0,
      tax: 9.2,
      reviewCount: 600,
      reviewSum: 2940,
    },
    {
      name: "Baby Alive Lily",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81T1N5Z5Y-L._AC_SL1500_.jpg",
      description: "Snackin' Lily baby doll",
      brand: "Hasbro",
      category: "dolls",
      number_in_stock: 50,
      colors: ["Blonde"],
      sizes: [],
      price: 26.99,
      shipping: 5.0,
      tax: 2.16,
      reviewCount: 3500,
      reviewSum: 16800,
    },

    // BUILDING SETS 
    {
      name: "LEGO Hogwarts Express",
      status: "active",
      src: "https://www.lego.com/cdn/cs/set/assets/blt56e18f8e0d9b4b1a/76405.jpg",
      description: "Harry Potter collectors set",
      brand: "LEGO",
      category: "buildingSets",
      number_in_stock: 10,
      colors: ["Red"],
      sizes: ["5129 pcs"],
      price: 499.99,
      shipping: 0.0,
      tax: 40.0,
      reviewCount: 120,
      reviewSum: 588,
    },
    {
      name: "Magna-Tiles 100pc",
      status: "active",
      src: "https://m.media-amazon.com/images/I/91rI-D-5NML._AC_SL1500_.jpg",
      description: "Magnetic building tiles",
      brand: "Magna-Tiles",
      category: "buildingSets",
      number_in_stock: 45,
      colors: ["Rainbow"],
      sizes: ["100pc"],
      price: 119.99,
      shipping: 0.0,
      tax: 9.6,
      reviewCount: 8900,
      reviewSum: 43610,
    },
    {
      name: "K'NEX Roller Coaster",
      status: "active",
      src: "https://m.media-amazon.com/images/I/91n8m7uK1vL._AC_SL1500_.jpg",
      description: "Thrill rides building kit",
      brand: "K'NEX",
      category: "buildingSets",
      number_in_stock: 30,
      colors: [],
      sizes: [],
      price: 49.99,
      shipping: 5.0,
      tax: 4.0,
      reviewCount: 640,
      reviewSum: 2880,
    },

    // REMOTE TOYS 
    {
      name: "DJI Mini 3 Pro",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61N3K4R4WPL._AC_SL1500_.jpg",
      description: "Lightweight camera drone",
      brand: "DJI",
      category: "remoteToys",
      number_in_stock: 22,
      colors: ["Gray"],
      sizes: [],
      price: 759.0,
      shipping: 0.0,
      tax: 60.72,
      reviewCount: 2100,
      reviewSum: 10080,
    },
    {
      name: "Traxxas Slash RC",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71R2o5D-4AL._AC_SL1500_.jpg",
      description: "Short-course racing truck",
      brand: "Traxxas",
      category: "remoteToys",
      number_in_stock: 12,
      colors: ["Blue", "Red"],
      sizes: ["1/10 Scale"],
      price: 229.95,
      shipping: 15.0,
      tax: 18.4,
      reviewCount: 840,
      reviewSum: 4032,
    },
    {
      name: "Air Hogs Zero Gravity",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71X8k7O1R8L._AC_SL1500_.jpg",
      description: "Wall climbing RC car",
      brand: "Air Hogs",
      category: "remoteToys",
      number_in_stock: 40,
      colors: ["Red"],
      sizes: [],
      price: 34.99,
      shipping: 5.0,
      tax: 2.8,
      reviewCount: 1100,
      reviewSum: 4620,
    },

    // SWIMMING 
    {
      name: "Speedo Vanquisher 2.0",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61n9yXU2vRL._AC_SL1500_.jpg",
      description: "Mirrored swim goggles",
      brand: "Speedo",
      category: "swimming",
      number_in_stock: 150,
      colors: ["Silver", "Blue"],
      sizes: ["One Size"],
      price: 22.0,
      shipping: 5.0,
      tax: 1.76,
      reviewCount: 12000,
      reviewSum: 55200,
    },
    {
      name: "Intex Easy Set Pool",
      status: "active",
      src: "https://m.media-amazon.com/images/I/91tN+7t+S2L._AC_SL1500_.jpg",
      description: "Inflatable family pool",
      brand: "Intex",
      category: "swimming",
      number_in_stock: 10,
      colors: ["Blue"],
      sizes: ["10ft x 30in"],
      price: 89.99,
      shipping: 20.0,
      tax: 7.2,
      reviewCount: 4500,
      reviewSum: 18000,
    },
    {
      name: "TYR Pull Float",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61H9j1R+8WL._AC_SL1500_.jpg",
      description: "Training swim buoy",
      brand: "TYR",
      category: "swimming",
      number_in_stock: 60,
      colors: ["Blue/White"],
      sizes: [],
      price: 14.99,
      shipping: 5.0,
      tax: 1.2,
      reviewCount: 540,
      reviewSum: 2430,
    },

    // SKATTING 
    {
      name: "Rollerblade Zetrablade",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81R3rR8M2qL._AC_SL1500_.jpg",
      description: "Men's inline skates",
      brand: "Rollerblade",
      category: "skatting",
      number_in_stock: 35,
      colors: ["Black"],
      sizes: ["9", "10", "11"],
      price: 129.0,
      shipping: 0.0,
      tax: 10.32,
      reviewCount: 2100,
      reviewSum: 9870,
    },
    {
      name: "Impala Quad Skates",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71u9S+H9SdL._AC_SL1500_.jpg",
      description: "Retro style roller skates",
      brand: "Impala",
      category: "skatting",
      number_in_stock: 45,
      colors: ["Pink", "Aqua"],
      sizes: ["7", "8"],
      price: 94.95,
      shipping: 0.0,
      tax: 7.6,
      reviewCount: 1800,
      reviewSum: 8280,
    },
    {
      name: "Santa Cruz Complete",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71mG-mE-v-L._AC_SL1500_.jpg",
      description: "Screaming Hand Skateboard",
      brand: "Santa Cruz",
      category: "skatting",
      number_in_stock: 20,
      colors: ["Blue"],
      sizes: ["8.0"],
      price: 109.95,
      shipping: 10.0,
      tax: 8.8,
      reviewCount: 410,
      reviewSum: 1886,
    },

    // TABLE TENNIS 
    {
      name: "STIGA Advantage Pro",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81fUvH1D1uL._AC_SL1500_.jpg",
      description: "Indoor table tennis table",
      brand: "STIGA",
      category: "tableTennis",
      number_in_stock: 5,
      colors: ["Blue"],
      sizes: ["Official Size"],
      price: 499.0,
      shipping: 100.0,
      tax: 39.92,
      reviewCount: 6200,
      reviewSum: 29760,
    },
    {
      name: "Butterfly Timo Boll",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71p0Wf4v-ML._AC_SL1500_.jpg",
      description: "Professional ping pong paddle",
      brand: "Butterfly",
      category: "tableTennis",
      number_in_stock: 50,
      colors: ["Black/Red"],
      sizes: [],
      price: 145.0,
      shipping: 0.0,
      tax: 11.6,
      reviewCount: 310,
      reviewSum: 1457,
    },
    {
      name: "JOOLA 60-Pack Balls",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81fH+1v+JXL._AC_SL1500_.jpg",
      description: "3-Star training balls",
      brand: "JOOLA",
      category: "tableTennis",
      number_in_stock: 100,
      colors: ["White"],
      sizes: ["40mm"],
      price: 32.99,
      shipping: 5.0,
      tax: 2.64,
      reviewCount: 1100,
      reviewSum: 5280,
    },

    // BATH 
    {
      name: "Lush Intergalactic",
      status: "active",
      src: "https://www.lush.com/dw/image/v2/BDDB_PRD/on/demandware.static/-/Sites-lushcosmetics-export-master/default/dw7e4f7a2d/images/hi-res/intergalactic-bath-bomb.jpg",
      description: "Peppermint bath bomb",
      brand: "Lush",
      category: "bath",
      number_in_stock: 500,
      colors: ["Blue/Gold"],
      sizes: ["200g"],
      price: 8.5,
      shipping: 5.0,
      tax: 0.68,
      reviewCount: 4200,
      reviewSum: 20580,
    },
    {
      name: "Dr Teal's Epsom Salt",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81k1L-vU-zL._AC_SL1500_.jpg",
      description: "Lavender soaking solution",
      brand: "Dr Teal's",
      category: "bath",
      number_in_stock: 300,
      colors: [],
      sizes: ["3lb"],
      price: 6.99,
      shipping: 5.0,
      tax: 0.56,
      reviewCount: 65000,
      reviewSum: 312000,
    },
    {
      name: "Aura Cacia Bubble Bath",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71Y8U2L6I+L._AC_SL1500_.jpg",
      description: "Lavender calming bubbles",
      brand: "Aura Cacia",
      category: "bath",
      number_in_stock: 120,
      colors: [],
      sizes: ["13oz"],
      price: 11.49,
      shipping: 5.0,
      tax: 0.92,
      reviewCount: 840,
      reviewSum: 3864,
    },

    // GROOMING 
    {
      name: "Manscaped Lawn Mower 4.0",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61M-F8pU-yL._AC_SL1500_.jpg",
      description: "Electric groin hair trimmer",
      brand: "Manscaped",
      category: "grooming",
      number_in_stock: 85,
      colors: ["Black"],
      sizes: [],
      price: 89.99,
      shipping: 0.0,
      tax: 7.2,
      reviewCount: 15000,
      reviewSum: 67500,
    },
    {
      name: "Philips OneBlade",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71t6W0-M7sL._AC_SL1500_.jpg",
      description: "Hybrid electric trimmer/shaver",
      brand: "Philips Norelco",
      category: "grooming",
      number_in_stock: 200,
      colors: ["Green"],
      sizes: [],
      price: 37.99,
      shipping: 0.0,
      tax: 3.04,
      reviewCount: 85000,
      reviewSum: 391000,
    },
    {
      name: "Beardbrand Utility Oil",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61N+5nN7L1L._AC_SL1500_.jpg",
      description: "Old Money beard oil",
      brand: "Beardbrand",
      category: "grooming",
      number_in_stock: 95,
      colors: [],
      sizes: ["1oz"],
      price: 25.0,
      shipping: 5.0,
      tax: 2.0,
      reviewCount: 320,
      reviewSum: 1536,
    },

    // COSMOTICS BAGS 
    {
      name: "Away The Cosmetics Case",
      status: "active",
      src: "https://www.awaytravel.com/dw/image/v2/BCLG_PRD/on/demandware.static/-/Sites-away-master-catalog/default/dw157a4072/images/CosmeticsCase_Black_1.jpg",
      description: "Structured travel makeup bag",
      brand: "Away",
      category: "cosmoticsBags",
      number_in_stock: 40,
      colors: ["Black"],
      sizes: [],
      price: 75.0,
      shipping: 0.0,
      tax: 6.0,
      reviewCount: 210,
      reviewSum: 1008,
    },
    {
      name: "Baggu Puffy Case",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61XG7C7Y-hL._AC_SL1200_.jpg",
      description: "Quilted nylon cosmetic bag",
      brand: "Baggu",
      category: "cosmoticsBags",
      number_in_stock: 110,
      colors: ["Green", "Blue"],
      sizes: ["Medium"],
      price: 18.0,
      shipping: 5.0,
      tax: 1.44,
      reviewCount: 540,
      reviewSum: 2592,
    },
    {
      name: "Longchamp Le Pliage Bag",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61I2H-P+ZkL._AC_SL1200_.jpg",
      description: "Nylon cosmetic pouch",
      brand: "Longchamp",
      category: "cosmoticsBags",
      number_in_stock: 35,
      colors: ["Navy"],
      sizes: [],
      price: 65.0,
      shipping: 0.0,
      tax: 5.2,
      reviewCount: 180,
      reviewSum: 864,
    },

    // BINS 
    {
      name: "Simplehuman 45L Step Bin",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71R2oYv-f6L._AC_SL1500_.jpg",
      description: "Stainless steel trash can",
      brand: "Simplehuman",
      category: "bins",
      number_in_stock: 25,
      colors: ["Silver"],
      sizes: ["45 Liter"],
      price: 149.99,
      shipping: 15.0,
      tax: 12.0,
      reviewCount: 11000,
      reviewSum: 52800,
    },
    {
      name: "Sterilite Latching Box",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71X8kEwK1dL._AC_SL1500_.jpg",
      description: "Clear storage bin",
      brand: "Sterilite",
      category: "bins",
      number_in_stock: 500,
      colors: ["Clear"],
      sizes: ["66 Qt"],
      price: 12.99,
      shipping: 5.0,
      tax: 1.04,
      reviewCount: 5400,
      reviewSum: 24840,
    },
    {
      name: "Rubbermaid Brute",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71U8k9Z+vXL._AC_SL1500_.jpg",
      description: "Commercial trash container",
      brand: "Rubbermaid",
      category: "bins",
      number_in_stock: 40,
      colors: ["Grey"],
      sizes: ["32 Gallon"],
      price: 45.0,
      shipping: 20.0,
      tax: 3.6,
      reviewCount: 3200,
      reviewSum: 15360,
    },

    // BATHROOM 
    {
      name: "Kohler Moxie Showerhead",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61W9-Z+N+SL._AC_SL1500_.jpg",
      description: "Bluetooth speaker showerhead",
      brand: "Kohler",
      category: "bathroom",
      number_in_stock: 18,
      colors: ["Chrome"],
      sizes: [],
      price: 199.0,
      shipping: 0.0,
      tax: 15.92,
      reviewCount: 420,
      reviewSum: 1848,
    },
    {
      name: "TOTO Washlet C5",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61vY8U2L6IL._AC_SL1500_.jpg",
      description: "Electronic bidet toilet seat",
      brand: "TOTO",
      category: "bathroom",
      number_in_stock: 12,
      colors: ["Cotton White"],
      sizes: ["Elongated"],
      price: 480.0,
      shipping: 20.0,
      tax: 38.4,
      reviewCount: 1100,
      reviewSum: 5280,
    },
    {
      name: "Sonicare DiamondClean",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71H2N2Z-uDL._AC_SL1500_.jpg",
      description: "Electric toothbrush",
      brand: "Philips",
      category: "bathroom",
      number_in_stock: 55,
      colors: ["Rose Gold"],
      sizes: [],
      price: 249.99,
      shipping: 0.0,
      tax: 20.0,
      reviewCount: 9500,
      reviewSum: 44650,
    },

    // SLEEPWEAR 
    {
      name: "Eberjey Gisele PJ",
      status: "active",
      src: "https://www.eberjey.com/cdn/shop/products/Gisele_Short_PJ_Set_Black_Front.jpg",
      description: "Soft Tencel pajama set",
      brand: "Eberjey",
      category: "sleepwear",
      number_in_stock: 60,
      colors: ["Black", "Navy"],
      sizes: ["S", "M", "L"],
      price: 128.0,
      shipping: 0.0,
      tax: 10.24,
      reviewCount: 850,
      reviewSum: 4165,
    },
    {
      name: "L.L. Bean Flannel PJs",
      status: "active",
      src: "https://cdni.llbean.net/is/image/wim/293226_482_41",
      description: "Classic scotch plaid flannel",
      brand: "L.L. Bean",
      category: "sleepwear",
      number_in_stock: 90,
      colors: ["Red Plaid"],
      sizes: ["M", "L", "XL"],
      price: 79.0,
      shipping: 0.0,
      tax: 6.32,
      reviewCount: 3200,
      reviewSum: 15360,
    },
    {
      name: "H&M Cotton Nightshirt",
      status: "active",
      src: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F8a%2F9b%2F8a9b8a9b8a9b8a9b8a9b8a9b8a9b8a9b8a9b8a9b.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url%5Bfile%3A%2Fproduct%2Fmain%5D",
      description: "Lightweight cotton nightgown",
      brand: "H&M",
      category: "sleepwear",
      number_in_stock: 150,
      colors: ["White/Striped"],
      sizes: ["S", "M"],
      price: 24.99,
      shipping: 5.0,
      tax: 2.0,
      reviewCount: 420,
      reviewSum: 1764,
    },

    // TRADITIONAL 
    {
      name: "Fabindia Silk Kurta",
      status: "active",
      src: "https://www.fabindia.com/dw/image/v2/BDBW_PRD/on/demandware.static/-/Sites-itemmaster_fabindia/default/dw1b3c8f8a/images/10001.jpg",
      description: "Handwoven silk tunic",
      brand: "Fabindia",
      category: "traditional",
      number_in_stock: 30,
      colors: ["Gold", "Maroon"],
      sizes: ["L", "XL"],
      price: 85.0,
      shipping: 10.0,
      tax: 6.8,
      reviewCount: 110,
      reviewSum: 506,
    },
    {
      name: "Sabyasachi Saree",
      status: "active",
      src: "https://www.sabyasachi.com/images/collection/floral-saree.jpg",
      description: "Designer floral saree",
      brand: "Sabyasachi",
      category: "traditional",
      number_in_stock: 5,
      colors: ["Floral"],
      sizes: ["Universal"],
      price: 1200.0,
      shipping: 50.0,
      tax: 96.0,
      reviewCount: 45,
      reviewSum: 220,
    },
    {
      name: "Kimono House Silk",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71Y8U2L6I+L._AC_SL1500_.jpg",
      description: "Authentic Japanese kimono",
      brand: "Kimono House",
      category: "traditional",
      number_in_stock: 10,
      colors: ["Blue/Floral"],
      sizes: ["Free Size"],
      price: 250.0,
      shipping: 20.0,
      tax: 20.0,
      reviewCount: 65,
      reviewSum: 318,
    },

    // KIDS CLOTHING 
    {
      name: "Carter's 5-Pack Bodysuits",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81fH+1v+JXL._AC_SL1500_.jpg",
      description: "Short-sleeve cotton onesies",
      brand: "Carter's",
      category: "kidsClothing",
      number_in_stock: 200,
      colors: ["Multi"],
      sizes: ["6M", "12M"],
      price: 18.0,
      shipping: 5.0,
      tax: 1.44,
      reviewCount: 15000,
      reviewSum: 72000,
    },
    {
      name: "OshKosh Denim Overalls",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81R3rR8M2qL._AC_SL1500_.jpg",
      description: "Classic hickory stripe bibs",
      brand: "OshKosh",
      category: "kidsClothing",
      number_in_stock: 85,
      colors: ["Blue"],
      sizes: ["2T", "3T", "4T"],
      price: 34.0,
      shipping: 5.0,
      tax: 2.72,
      reviewCount: 3200,
      reviewSum: 15360,
    },
    {
      name: "Patagonia Kids Synchilla",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71u9S+H9SdL._AC_SL1500_.jpg",
      description: "Snap-T fleece pullover",
      brand: "Patagonia",
      category: "kidsClothing",
      number_in_stock: 40,
      colors: ["Green"],
      sizes: ["S", "M"],
      price: 79.0,
      shipping: 0.0,
      tax: 6.32,
      reviewCount: 840,
      reviewSum: 4032,
    },

    // HAIR (Accessories) 
    {
      name: "Slip Silk Scrunchies",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61I2H-P+ZkL._AC_SL1200_.jpg",
      description: "Pure silk hair ties",
      brand: "Slip",
      category: "hair",
      number_in_stock: 150,
      colors: ["Pink", "Gold"],
      sizes: ["Large"],
      price: 39.0,
      shipping: 5.0,
      tax: 3.12,
      reviewCount: 1100,
      reviewSum: 5280,
    },
    {
      name: "Mason Pearson Brush",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71Y8U2L6I+L._AC_SL1500_.jpg",
      description: "Boar bristle hair brush",
      brand: "Mason Pearson",
      category: "hair",
      number_in_stock: 25,
      colors: ["Ruby"],
      sizes: ["Junior"],
      price: 175.0,
      shipping: 0.0,
      tax: 14.0,
      reviewCount: 450,
      reviewSum: 2160,
    },
    {
      name: "Scunci Claw Clips",
      status: "active",
      src: "https://m.media-amazon.com/images/I/81fUvH1D1uL._AC_SL1500_.jpg",
      description: "No-slip grip clips",
      brand: "Scunci",
      category: "hair",
      number_in_stock: 300,
      colors: ["Tortoise"],
      sizes: ["Medium"],
      price: 7.99,
      shipping: 5.0,
      tax: 0.64,
      reviewCount: 8500,
      reviewSum: 39100,
    },

    // SUNGLASSES 
    {
      name: "Ray-Ban Aviator",
      status: "active",
      src: "https://m.media-amazon.com/images/I/51HDeJ2UfPL._AC_SL1000_.jpg",
      description: "Classic gold frame aviators",
      brand: "Ray-Ban",
      category: "sunglasses",
      number_in_stock: 60,
      colors: ["Gold"],
      sizes: ["58mm"],
      price: 163.0,
      shipping: 0.0,
      tax: 13.04,
      reviewCount: 4200,
      reviewSum: 20160,
    },
    {
      name: "Oakley Holbrook",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61N3K4R4WPL._AC_SL1500_.jpg",
      description: "Polarized sport sunglasses",
      brand: "Oakley",
      category: "sunglasses",
      number_in_stock: 45,
      colors: ["Matte Black"],
      sizes: ["Standard"],
      price: 150.0,
      shipping: 0.0,
      tax: 12.0,
      reviewCount: 3100,
      reviewSum: 14880,
    },
    {
      name: "Quay Australia High Key",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71R2o5D-4AL._AC_SL1500_.jpg",
      description: "Oversized aviator frames",
      brand: "Quay",
      category: "sunglasses",
      number_in_stock: 100,
      colors: ["Black Smoke"],
      sizes: [],
      price: 65.0,
      shipping: 5.0,
      tax: 5.2,
      reviewCount: 840,
      reviewSum: 3864,
    },

    // BELTS 
    {
      name: "Gucci Double G Belt",
      status: "active",
      src: "https://images.clothes.com/is/image/Gucci/406831_DJ20T_1000_001_Light",
      description: "Leather belt with gold buckle",
      brand: "Gucci",
      category: "belts",
      number_in_stock: 15,
      colors: ["Black"],
      sizes: ["80", "90", "100"],
      price: 490.0,
      shipping: 0.0,
      tax: 39.2,
      reviewCount: 320,
      reviewSum: 1568,
    },
    {
      name: "Carhartt Leather Belt",
      status: "active",
      src: "https://m.media-amazon.com/images/I/91PshO-rSXL._AC_SL1500_.jpg",
      description: "Rugged heavy-duty leather",
      brand: "Carhartt",
      category: "belts",
      number_in_stock: 120,
      colors: ["Brown"],
      sizes: ["34", "36", "38"],
      price: 35.0,
      shipping: 5.0,
      tax: 2.8,
      reviewCount: 18000,
      reviewSum: 84600,
    },
    {
      name: "Arc'teryx Conveyor Belt",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71X8k7O1R8L._AC_SL1500_.jpg",
      description: "Textured webbing belt",
      brand: "Arc'teryx",
      category: "belts",
      number_in_stock: 50,
      colors: ["Black", "Tui"],
      sizes: ["M", "L"],
      price: 40.0,
      shipping: 5.0,
      tax: 3.2,
      reviewCount: 640,
      reviewSum: 2880,
    },

    // EARBUDS 
    {
      name: "AirPods Pro 2",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61f17P1O5nL._AC_SL1500_.jpg",
      description: "Wireless noise cancelling",
      brand: "Apple",
      category: "earbuds",
      number_in_stock: 150,
      colors: ["White"],
      sizes: [],
      price: 249.0,
      shipping: 0.0,
      tax: 19.92,
      reviewCount: 45000,
      reviewSum: 216000,
    },
    {
      name: "Sony WF-1000XM5",
      status: "active",
      src: "https://m.media-amazon.com/images/I/51HDeJ2UfPL._AC_SL1000_.jpg",
      description: "Best-in-class noise canceling",
      brand: "Sony",
      category: "earbuds",
      number_in_stock: 60,
      colors: ["Black", "Silver"],
      sizes: [],
      price: 299.0,
      shipping: 0.0,
      tax: 23.92,
      reviewCount: 1200,
      reviewSum: 5640,
    },
    {
      name: "Jabara Elite 7 Active",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61N3K4R4WPL._AC_SL1500_.jpg",
      description: "Workout-ready earbuds",
      brand: "Jabra",
      category: "earbuds",
      number_in_stock: 85,
      colors: ["Navy"],
      sizes: [],
      price: 179.0,
      shipping: 0.0,
      tax: 14.32,
      reviewCount: 3100,
      reviewSum: 13950,
    },

    // VR 
    {
      name: "Meta Quest 3",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61SOn77JBWL._SL1500_.jpg",
      description: "Mixed reality VR headset",
      brand: "Meta",
      category: "VR",
      number_in_stock: 45,
      colors: ["White"],
      sizes: ["128GB", "512GB"],
      price: 499.99,
      shipping: 0.0,
      tax: 40.0,
      reviewCount: 850,
      reviewSum: 4080,
    },
    {
      name: "PlayStation VR2",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61y8U2L6I+L._AC_SL1500_.jpg",
      description: "Next-gen VR for PS5",
      brand: "Sony",
      category: "VR",
      number_in_stock: 20,
      colors: ["White"],
      sizes: [],
      price: 549.99,
      shipping: 0.0,
      tax: 44.0,
      reviewCount: 1100,
      reviewSum: 5060,
    },
    {
      name: "Valve Index Kit",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71R2o5D-4AL._AC_SL1500_.jpg",
      description: "High-fidelity PC VR",
      brand: "Valve",
      category: "VR",
      number_in_stock: 5,
      colors: ["Black"],
      sizes: [],
      price: 999.0,
      shipping: 30.0,
      tax: 79.92,
      reviewCount: 640,
      reviewSum: 3072,
    },

    // SECURITY CAMERAS 
    {
      name: "Ring Video Doorbell",
      status: "active",
      src: "https://m.media-amazon.com/images/I/71X8k7O1R8L._AC_SL1500_.jpg",
      description: "1080p HD video doorbell",
      brand: "Ring",
      category: "securityCameras",
      number_in_stock: 200,
      colors: ["Satin Nickel"],
      sizes: [],
      price: 99.99,
      shipping: 0.0,
      tax: 8.0,
      reviewCount: 150000,
      reviewSum: 690000,
    },
    {
      name: "Arlo Pro 4",
      status: "active",
      src: "https://m.media-amazon.com/images/I/61f17P1O5nL._AC_SL1500_.jpg",
      description: "Wire-free 2K security cam",
      brand: "Arlo",
      category: "securityCameras",
      number_in_stock: 40,
      colors: ["White"],
      sizes: ["3-Pack"],
      price: 549.99,
      shipping: 0.0,
      tax: 44.0,
      reviewCount: 3200,
      reviewSum: 14400,
    },
    {
      name: "Google Nest Cam",
      status: "active",
      src: "https://m.media-amazon.com/images/I/51HDeJ2UfPL._AC_SL1000_.jpg",
      description: "Indoor/Outdoor battery cam",
      brand: "Google",
      category: "securityCameras",
      number_in_stock: 70,
      colors: ["Snow"],
      sizes: [],
      price: 179.99,
      shipping: 0.0,
      tax: 14.4,
      reviewCount: 2100,
      reviewSum: 9450,
    },
  ];
*/
  const orders = [
    // ---------------- SAMPLE ORDER ----------------
    {
      order_date: new Date("2026-02-24T10:30:00Z"),
      delivery_date: new Date("2026-03-01"),
      total_price: 165.0,
      payment_method: "Credit Card",
      name_on_bank: "John Doe",
      accountNo: "1234567890",
      paid_status: "Pending",
      user_id: 1,
      address_id: 1,
      order_items: [
        {
          product_id: 1, // assuming product with id 1 exists
          quantity: 1,
          price: 50.0,
        },
        {
          product_id: 2, // assuming product with id 2 exists
          quantity: 2,
          price: 57.5,
        },
      ],
    },
  ];
  for (const order of orders) {
    h;
    await prisma.orders.create({
      data: order,
    });
  }

  console.log("✅ Mock data seeded successfully.");
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
